### ISSUE TITLE
Install WP theme

### ISSUE THREAD

**Issue by kelle** [arceli/website#2]
will reach out to Stephanie and maybe need to add some PressForward folks to this repo.

**Comment by kelle** [comment]
Stephanie said we could use this one which they developed and support: https://github.com/DigitalHumanitiesNow/DHNow-Theme

We could use our own theme, but for simplicity, let's just use theirs for now.

But we need someone to install it. @libcce, @jonathansick  - Do you have any nominations for someone who wants to/is able to get their hands dirty with the WP or should I find someone?

**Comment by jonathansick** [comment]
I don't have any WP experience, so I'm probably not your first choice. Also noticed that the link to their install guide (https://github.com/DigitalHumanitiesNow/DHNow-Theme/blob/master) doesn't work.

**Comment by libcce** [comment]
It should be fairly easy, package their theme
https://github.com/DigitalHumanitiesNow/DHNow-Theme as .zip and upload it
under Appearance, add new/upload. You can give me admin rights and I can do
it. It should work but that broken guide link is not a good sign!

On Thu, Jul 9, 2015 at 12:43 PM, Jonathan Sick notifications@github.com
wrote:

> I don't have any WP experience, so I'm probably not your first choice.
> Also noticed that the link to their install guide (
> https://github.com/DigitalHumanitiesNow/DHNow-Theme/blob/master) doesn't
> work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/website/issues/2#issuecomment-120065000.

## 

Christopher Erdmann, Head Librarian
Harvard-Smithsonian Center for Astrophysics, John G. Wolbach Library
cerdmann@cfa.harvard.edu | 617-495-7289 | @libcce
_http://library.cfa.harvard.edu/ http://library.cfa.harvard.edu/_
http://orcid.org/0000-0003-2554-180X

**Comment by kelle** [comment]
@mrawls Want to take the lead on this?

**Comment by kelle** [comment]
I realize that we're waiting on WP accounts...I'll nudge @elambrid about #3

**Comment by mrawls** [comment]
@kelle Sure, ping me when an admin account is created for me on the site, and I'll see if I can get that theme installed. We may want to switch to a different theme later but this looks like a great starting point.

**Comment by kelle** [comment]
from Stephanie: 
So you'll want to pull the theme from this repository: https://github.com/PressForward/PressForward-TurnKey-Theme. Everything there should be working. I'm sorry; I directed you to the DHNow specific branch, not the more general PressForward one. (The link that's broken there will be fixed shortly; she's been updating a lot on the DHNow specific page this week.) Let me know if you have any questions about that.

**Comment by mrawls** [comment]
Nice, that makes sense. I await a user account on the site and then I'll see what I can do.

**Comment by elambrid** [comment]
sorry for the delay in wp-admin rights folks, kelle is now admin, and you all should expect to receive your privileges shortly!

**Comment by mrawls** [comment]
Any updates, @elambrid or @kelle? I'm happy to install the theme, but I need WP login info. I'll be mostly offline July 22-28, after which I'll have more time to play with this. Thanks!

**Comment by kelle** [comment]
All yall now have admin accounts on the WP. Pswds should have been emailed to you.
http://arce.li/wp-login.php

**Comment by libcce** [comment]
I had a look, not seeing the WP message?

**Comment by kelle** [comment]
I used your github usernames and I just emailed your password to you @libcce

**Comment by mrawls** [comment]
Hi, I haven't gotten a message from WP either. I will have some time to work on this next week.

**Comment by kelle** [comment]
I emailed password to @mrawls. I think our host's email functionality is not yet setup. (subject for another day...)

**Comment by mrawls** [comment]
Theme install update. I am able to login to Wordpress now, but the PressForward TurnKey theme is 3MB (too large to upload the easy way, apparently). The install guide says the file size is a known issue, and I should "please upload the theme via your ftp client or clone the theme into your wp-content/themes directory using git rather than through the WordPress theme upload option." However, I'm not able to connect to arceli with FTP... is our server set up to allow it? Thanks.

**Comment by elambrid** [comment]
hey, i'll take a look meredith
-erini

**Comment by elambrid** [comment]
Hey @mrawls ! Sftp is set up, and you have an account on the host:
sftp mrawls@arce.li
temporary password: mereditharceli

location of arce.li wordpress on the server:

/var/www/arce.li/public_html/wordpress/

(to change > passwd mrawls)

**Comment by mrawls** [comment]
Thanks @elambrid, now I can login with my FTP client (Cyberduck) and see the directory tree, but when I try to upload a file anywhere it says "permission denied, please contact your web hosting service provider for assistance."

**Comment by elambrid** [comment]
Hey you are now a sudoer meredith!

-Erini

**Comment by mrawls** [comment]
Thanks @elambrid, but unfortunately when I try to initiate a file upload it still gives the same error.

**Comment by elambrid** [comment]
Very odd, you are in the sudoer group server wide, this includes ftp.arce.li

I have logged in as you an able to confirm your sudo abilities. I am a
linux user, so i can't test with cyberduck, but i used linux connect to
server ability and see the gui directory tree, I am able to create files
and folders as you as well.

Is there any other info you could give, so I could try to debug more?

i was using username: mrawls pw:mereditharceli

**Comment by mrawls** [comment]
Ah, I can put files in my home directory, but not in the wordpress directory.

**Comment by elambrid** [comment]
hey so I just did it as you! while you were doing the cp, did you sudo in?
I did it directly through terminal. I believe most ftp gui have built in
locks against root changes.

**Comment by mrawls** [comment]
Got it, didn't consider that, command line it is... thanks for your help, should be good to go!

**Comment by elambrid** [comment]
sweet! let me know if you need anything else!
-erini

**Comment by kelle** [comment]
btw, I'm going to a PressForward conference next week Thur/Friday and a big topic is the WP theme. @mrawls, if you have any questions or comments before then, please let me know. Maybe you could also skype into the presentation that's specifically about the theme...it's scheduled for 3:30 ET on Thursday.

**Comment by mrawls** [comment]
That's great @kelle! No specific questions at the moment, beyond the basic "well, we have a blank template, where to begin?" ... unfortunately, I will be assisting with a software carpentry workshop next week on Thursday and Friday so I don't think I can join. Please share what you learn!
